// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	AdminTokenScopes = "AdminToken.Scopes"
	UserTokenScopes  = "UserToken.Scopes"
)

// Defines values for ErrorResponseErrorCode.
const (
	NOCANDIDATE ErrorResponseErrorCode = "NO_CANDIDATE"
	NOTASSIGNED ErrorResponseErrorCode = "NOT_ASSIGNED"
	NOTFOUND    ErrorResponseErrorCode = "NOT_FOUND"
	PREXISTS    ErrorResponseErrorCode = "PR_EXISTS"
	PRMERGED    ErrorResponseErrorCode = "PR_MERGED"
	TEAMEXISTS  ErrorResponseErrorCode = "TEAM_EXISTS"
)

// Defines values for PullRequestStatus.
const (
	PullRequestStatusMERGED PullRequestStatus = "MERGED"
	PullRequestStatusOPEN   PullRequestStatus = "OPEN"
)

// Defines values for PullRequestShortStatus.
const (
	PullRequestShortStatusMERGED PullRequestShortStatus = "MERGED"
	PullRequestShortStatusOPEN   PullRequestShortStatus = "OPEN"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// PullRequest defines model for PullRequest.
type PullRequest struct {
	// AssignedReviewers user_id назначенных ревьюверов (0..2)
	AssignedReviewers []string          `json:"assigned_reviewers"`
	AuthorId          string            `json:"author_id"`
	CreatedAt         *time.Time        `json:"createdAt"`
	MergedAt          *time.Time        `json:"mergedAt"`
	PullRequestId     string            `json:"pull_request_id"`
	PullRequestName   string            `json:"pull_request_name"`
	Status            PullRequestStatus `json:"status"`
}

// PullRequestStatus defines model for PullRequest.Status.
type PullRequestStatus string

// PullRequestShort defines model for PullRequestShort.
type PullRequestShort struct {
	AuthorId        string                 `json:"author_id"`
	PullRequestId   string                 `json:"pull_request_id"`
	PullRequestName string                 `json:"pull_request_name"`
	Status          PullRequestShortStatus `json:"status"`
}

// PullRequestShortStatus defines model for PullRequestShort.Status.
type PullRequestShortStatus string

// Team defines model for Team.
type Team struct {
	Members  []TeamMember `json:"members"`
	TeamName string       `json:"team_name"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// User defines model for User.
type User struct {
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// TeamNameQuery defines model for TeamNameQuery.
type TeamNameQuery = string

// UserIdQuery defines model for UserIdQuery.
type UserIdQuery = string

// PostPullRequestCreateJSONBody defines parameters for PostPullRequestCreate.
type PostPullRequestCreateJSONBody struct {
	AuthorId        string `json:"author_id"`
	PullRequestId   string `json:"pull_request_id"`
	PullRequestName string `json:"pull_request_name"`
}

// PostPullRequestMergeJSONBody defines parameters for PostPullRequestMerge.
type PostPullRequestMergeJSONBody struct {
	PullRequestId string `json:"pull_request_id"`
}

// PostPullRequestReassignJSONBody defines parameters for PostPullRequestReassign.
type PostPullRequestReassignJSONBody struct {
	OldUserId     string `json:"old_user_id"`
	PullRequestId string `json:"pull_request_id"`
}

// GetTeamGetParams defines parameters for GetTeamGet.
type GetTeamGetParams struct {
	// TeamName Уникальное имя команды
	TeamName TeamNameQuery `form:"team_name" json:"team_name"`
}

// GetUsersGetReviewParams defines parameters for GetUsersGetReview.
type GetUsersGetReviewParams struct {
	// UserId Идентификатор пользователя
	UserId UserIdQuery `form:"user_id" json:"user_id"`
}

// PostUsersSetIsActiveJSONBody defines parameters for PostUsersSetIsActive.
type PostUsersSetIsActiveJSONBody struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
}

// PostPullRequestCreateJSONRequestBody defines body for PostPullRequestCreate for application/json ContentType.
type PostPullRequestCreateJSONRequestBody PostPullRequestCreateJSONBody

// PostPullRequestMergeJSONRequestBody defines body for PostPullRequestMerge for application/json ContentType.
type PostPullRequestMergeJSONRequestBody PostPullRequestMergeJSONBody

// PostPullRequestReassignJSONRequestBody defines body for PostPullRequestReassign for application/json ContentType.
type PostPullRequestReassignJSONRequestBody PostPullRequestReassignJSONBody

// PostTeamAddJSONRequestBody defines body for PostTeamAdd for application/json ContentType.
type PostTeamAddJSONRequestBody = Team

// PostUsersSetIsActiveJSONRequestBody defines body for PostUsersSetIsActive for application/json ContentType.
type PostUsersSetIsActiveJSONRequestBody PostUsersSetIsActiveJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
	// (POST /pullRequest/create)
	PostPullRequestCreate(ctx echo.Context) error
	// Пометить PR как MERGED (идемпотентная операция)
	// (POST /pullRequest/merge)
	PostPullRequestMerge(ctx echo.Context) error
	// Переназначить конкретного ревьювера на другого из его команды
	// (POST /pullRequest/reassign)
	PostPullRequestReassign(ctx echo.Context) error
	// Получить статистику назначений ревьюверов по пользователям
	// (GET /stats/assignments)
	GetStatsAssignments(ctx echo.Context) error
	// Создать команду с участниками (создаёт/обновляет пользователей)
	// (POST /team/add)
	PostTeamAdd(ctx echo.Context) error
	// Получить команду с участниками
	// (GET /team/get)
	GetTeamGet(ctx echo.Context, params GetTeamGetParams) error
	// Получить PR'ы, где пользователь назначен ревьювером
	// (GET /users/getReview)
	GetUsersGetReview(ctx echo.Context, params GetUsersGetReviewParams) error
	// Установить флаг активности пользователя
	// (POST /users/setIsActive)
	PostUsersSetIsActive(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostPullRequestCreate converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestCreate(ctx echo.Context) error {
	var err error

	ctx.Set(AdminTokenScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestCreate(ctx)
	return err
}

// PostPullRequestMerge converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestMerge(ctx echo.Context) error {
	var err error

	ctx.Set(AdminTokenScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestMerge(ctx)
	return err
}

// PostPullRequestReassign converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestReassign(ctx echo.Context) error {
	var err error

	ctx.Set(AdminTokenScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestReassign(ctx)
	return err
}

// GetStatsAssignments converts echo context to params.
func (w *ServerInterfaceWrapper) GetStatsAssignments(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStatsAssignments(ctx)
	return err
}

// PostTeamAdd converts echo context to params.
func (w *ServerInterfaceWrapper) PostTeamAdd(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTeamAdd(ctx)
	return err
}

// GetTeamGet converts echo context to params.
func (w *ServerInterfaceWrapper) GetTeamGet(ctx echo.Context) error {
	var err error

	ctx.Set(AdminTokenScopes, []string{})

	ctx.Set(UserTokenScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamGetParams
	// ------------- Required query parameter "team_name" -------------

	err = runtime.BindQueryParameter("form", true, true, "team_name", ctx.QueryParams(), &params.TeamName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter team_name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTeamGet(ctx, params)
	return err
}

// GetUsersGetReview converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsersGetReview(ctx echo.Context) error {
	var err error

	ctx.Set(AdminTokenScopes, []string{})

	ctx.Set(UserTokenScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersGetReviewParams
	// ------------- Required query parameter "user_id" -------------

	err = runtime.BindQueryParameter("form", true, true, "user_id", ctx.QueryParams(), &params.UserId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsersGetReview(ctx, params)
	return err
}

// PostUsersSetIsActive converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersSetIsActive(ctx echo.Context) error {
	var err error

	ctx.Set(AdminTokenScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersSetIsActive(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/pullRequest/create", wrapper.PostPullRequestCreate)
	router.POST(baseURL+"/pullRequest/merge", wrapper.PostPullRequestMerge)
	router.POST(baseURL+"/pullRequest/reassign", wrapper.PostPullRequestReassign)
	router.GET(baseURL+"/stats/assignments", wrapper.GetStatsAssignments)
	router.POST(baseURL+"/team/add", wrapper.PostTeamAdd)
	router.GET(baseURL+"/team/get", wrapper.GetTeamGet)
	router.GET(baseURL+"/users/getReview", wrapper.GetUsersGetReview)
	router.POST(baseURL+"/users/setIsActive", wrapper.PostUsersSetIsActive)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xabW8buRH+KwRb4HKAYslKUqD6pkt8qT/EUWUdUNQwDFrL2HuRdpUlNz3DEJDI115b",
	"B3XvWxHgLgjuDyiKVSt+kf/C8B8VQ672RVqtpchxivsSKLtccjh85plnht6ndbfZch3uSEFL+7TFPNbk",
	"knv6fzXOmmusyf/oc28PH1hc1D27JW3XoSUKv8AFDOAUunCmXsEFDKFPYADn6ojAKQzhHLpwAcfqkOao",
	"jV880xPlqMOanJao5Ky5pX/nqMef+bbHLVqSns9zVNR3eZPhonKvhYOF9Gxnh7bbOfqN4N6qNc2q/8Ax",
	"9OFCdWCgvjf2qQ4M1QsClzDUpp7AEHr6cR/O1NEU83zBvS3bmsu49uilduCK57lelYuW6wiOD/h3rNlq",
	"mJ/4Dn/UXQunWHtc2/r68TdrD2iONrkQbAefely4vlfnxHEleeL6jqU90PLcFvekzUViquRjM/E+5Y7f",
	"pKUNWlspP9pa+dPqem2d5milmvj9aKX6cAXXRjvK6+urD9eC/27dL689WH1Qrq0Eb42Vm7nxzcfsTju1",
	"yIkbxrRofDSXu/0tr8uJ8WaHk8NytOI3GlX+zOdCTnqACWHvONza8vhzm/8lgHUSL8EpE7iALpzgv+oH",
	"xA9cqEP1V6JeQB966pX6F/Sgr14gcsitwtJS8UuEjeRNkbLd0FDmeWwP/898uetqOKWNrnucSW6V9R6e",
	"uF6TSVqiFpP8trR1fDh+o8G2EToGgim+93YWm6HlNxpbnvHlNEMTY0ycpIwSkklfxLH3uLKyRnM0QNkk",
	"dsbOe9yUtIXjPg2XzKWd+RW4Wd91vTTwZJ7Yr8FZaX5Bzp/0RZM3t4PoCSH/W48/oSX6m3yUQvIB9+Vx",
	"lkf6m7RYiHj/SqKIp4iREdPMDhacMN4WW6wu7efx5bZdt8GZg5+OaD7tbPDdbIZGySL8JhdbOc1mTGNz",
	"W5vlu0+6l/hJZO0LJ7OdJ65expbIN7RSJdUgGklZx2eTO5Ksc++5XefkVo0LSWpMPM2Rr1mjQYqF4j2k",
	"1+fcE4all5cKSwXchdviDmvZtETvLBWW7iDYmdzVnsu3opjOG0bV7nVNakAnMyT9VQtNcoWMccB9M9z4",
	"gQv5lWvtmRzqSO7o71mr1bDreob8twKtSuTzGF1Qf5mmMARtebeXC4Xl1AAt0bJlEcGZV9+l7bjE+Bys",
	"tCDDpKMiqaL0A6OM9MaKheX5HN7ypqX4DeoXEbx30JDrPJeIrA1HtzMOypiXRZJx6dJup7osKVUqVaJe",
	"whBO4BiVNR7m3cLdGbwW2ZhlT1KtpqwP/4aekdL5uL6HLoqnvlFQHwL1fWis+/18ZzouiuMiNRLFlSqx",
	"LcIaHmfWHuHf2UKKsbNYaJ/o5wP4L/SJeqkO1D+gr16qDvTUAfRVx6zE675nyz1a2tinZatpOzX3KXdo",
	"aWOzvZmjwm82GVYnFN6ODkx11CtSqRIYEOgaR6IHdZ3yAy4Bp/gqLkMH+hs4hiEppitRGMDJWLEVzq5e",
	"QBeJm+3omIjBTdBN3ESCMLV+nJkvH+nRC9Dl9CjMiqkr6e0K4vo4YircDDFFCp5iAry9XLhdvFtbLpbu",
	"3C3d+92fr426Al158+QFPc1fOpiG6kh3DwZkZM4NkxnaM85ac4b2Gx12fR3Bo+A+hS6cBnsit2CgJz6H",
	"SxjqbsOF6ujYPiIwhEsdxl31Nxiooy9nD1WPG3DNHK3V0QcLBKzbiKAcgLaYCckMeOFcWVJ14TjPJZb4",
	"/FGPOtW/98nlCO6h1WB1bm1tI0L9e/T6gnxs8ow+yhB6MIT3MJzMWTohZR+lR5Mrbc5ALvBGz96faOIM",
	"MMJ76tC0/jDg0b7PQjYDOMP8nt6DfJVGRnMKqKBSxySiTY+I6iezBpwg75xrGjoy0gJ56SWcQZ+EDcDn",
	"rOFPE2PhoEiM1ZnjuJKMOIm4DjE2kErVuMJx7zPHsq2gHkvapTpa32BOUAdwGXTdNI2itBwY5YS+yjJt",
	"rEsZWee4xFSqJICULjzrI3uI7RAsbEeGynIQv2OGvsk8tHfqEM4mGohpgu08exOJzmu8CRzUzrbQfeAR",
	"yRDpErlri8DT1yeA4SfoqhfqQP09CqJjk+zCxihcYjhDD3FNglSWEn/qaO6kOjlToINR5l7AKb7WaXQa",
	"x+ijIHCMW8AhephRyn3ze/x2IiPxIsWKPAu7FjrKdnhK0n3I5ToOLsfGLpZVNnCojwPvxXo7mDfaufDV",
	"ncSrItX+DHEQtuvG7wZ8s/7Ywb/WNBkUJFjzoLcmSfVDROO2I/mO6fNNT+lTG0zGjrTuWLJpmILRt6oT",
	"VE9oqL7nSTdV4288lg9CWOnPExOpg9SJplRgl+iiKTdLOuBH4PoDZw25G8AKWSfPLCtbw9U4a5YtaxHd",
	"FrZuNxK9RXMHkMBUvEVIyw27zjXMsj4qJj/6yt3W8Is1KWmL7ZlQmJmeaiEhX3PHSAa97c/tkm1Wf8qD",
	"m7xp4mxk6wyOmkUfvU60a+JdJOgaoVFYrFOTvFyMcle470/Yrxnf3VW9m2nNmURaOCDqJdE00dUzjK66",
	"z2FAbkUOVD+qTh6G8C7QvRj0WtSkMgL04UO80MMTFHFGCBLLtPyC4x9yqbve0U39Rrr/oiH55E0+4nGx",
	"Yuf/JoLm55Qx6PwM79Q/oQ+neGZJWXDj7dXX2T1VjNQrpFRuX98qZTUs4qlvVsBPQSwekkDImsudLOCi",
	"VeJhOHJe/Mb/4mNx9MbLarP8J63KN8cF2mwNztlvWyfuslPuXD9CmyWNmakMfwuXKKNgCKekUv0iFEip",
	"f3VzzWCuVL9QhzkC7zFaMuvsmcq0EeA1chOAF1yuinJ4RztdvelP12OjF5BxMcJ8whqCz46pj77+ngqM",
	"q65/r7mz5gf35JMuSEsJV6aSDFeNVsoKNn1rP5vo+jmmCn40hTN8mIpMk2+WbzDf6PZLXjfFDPIDA7tw",
	"jKwPF+ZOCiufDoZ01JW6yaz4ZvaG2VyNhl9M4RecUFALfg9n0IX36INTXQz28L0pDLP+fnCCLdrhs/3R",
	"3xOa1Im0Fjwwg2MPEu2H2POgcmxvtv8XAAD//+GWI3OxKQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
