// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	AdminTokenScopes = "AdminToken.Scopes"
	UserTokenScopes  = "UserToken.Scopes"
)

// Defines values for ErrorResponseErrorCode.
const (
	NOCANDIDATE ErrorResponseErrorCode = "NO_CANDIDATE"
	NOTASSIGNED ErrorResponseErrorCode = "NOT_ASSIGNED"
	NOTFOUND    ErrorResponseErrorCode = "NOT_FOUND"
	PREXISTS    ErrorResponseErrorCode = "PR_EXISTS"
	PRMERGED    ErrorResponseErrorCode = "PR_MERGED"
	TEAMEXISTS  ErrorResponseErrorCode = "TEAM_EXISTS"
)

// Defines values for PullRequestStatus.
const (
	PullRequestStatusMERGED PullRequestStatus = "MERGED"
	PullRequestStatusOPEN   PullRequestStatus = "OPEN"
)

// Defines values for PullRequestShortStatus.
const (
	PullRequestShortStatusMERGED PullRequestShortStatus = "MERGED"
	PullRequestShortStatusOPEN   PullRequestShortStatus = "OPEN"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// PullRequest defines model for PullRequest.
type PullRequest struct {
	// AssignedReviewers user_id назначенных ревьюверов (0..2)
	AssignedReviewers []string          `json:"assigned_reviewers"`
	AuthorId          string            `json:"author_id"`
	CreatedAt         *time.Time        `json:"createdAt"`
	MergedAt          *time.Time        `json:"mergedAt"`
	PullRequestId     string            `json:"pull_request_id"`
	PullRequestName   string            `json:"pull_request_name"`
	Status            PullRequestStatus `json:"status"`
}

// PullRequestStatus defines model for PullRequest.Status.
type PullRequestStatus string

// PullRequestShort defines model for PullRequestShort.
type PullRequestShort struct {
	AuthorId        string                 `json:"author_id"`
	PullRequestId   string                 `json:"pull_request_id"`
	PullRequestName string                 `json:"pull_request_name"`
	Status          PullRequestShortStatus `json:"status"`
}

// PullRequestShortStatus defines model for PullRequestShort.Status.
type PullRequestShortStatus string

// Team defines model for Team.
type Team struct {
	Members  []TeamMember `json:"members"`
	TeamName string       `json:"team_name"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// User defines model for User.
type User struct {
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// TeamNameQuery defines model for TeamNameQuery.
type TeamNameQuery = string

// UserIdQuery defines model for UserIdQuery.
type UserIdQuery = string

// PostPullRequestCreateJSONBody defines parameters for PostPullRequestCreate.
type PostPullRequestCreateJSONBody struct {
	AuthorId        string `json:"author_id"`
	PullRequestId   string `json:"pull_request_id"`
	PullRequestName string `json:"pull_request_name"`
}

// PostPullRequestMergeJSONBody defines parameters for PostPullRequestMerge.
type PostPullRequestMergeJSONBody struct {
	PullRequestId string `json:"pull_request_id"`
}

// PostPullRequestReassignJSONBody defines parameters for PostPullRequestReassign.
type PostPullRequestReassignJSONBody struct {
	OldUserId     string `json:"old_user_id"`
	PullRequestId string `json:"pull_request_id"`
}

// PostTeamDeactivateJSONBody defines parameters for PostTeamDeactivate.
type PostTeamDeactivateJSONBody struct {
	// TeamName Уникальное имя команды
	TeamName string `json:"team_name"`
}

// GetTeamGetParams defines parameters for GetTeamGet.
type GetTeamGetParams struct {
	// TeamName Уникальное имя команды
	TeamName TeamNameQuery `form:"team_name" json:"team_name"`
}

// GetUsersGetReviewParams defines parameters for GetUsersGetReview.
type GetUsersGetReviewParams struct {
	// UserId Идентификатор пользователя
	UserId UserIdQuery `form:"user_id" json:"user_id"`
}

// PostUsersSetIsActiveJSONBody defines parameters for PostUsersSetIsActive.
type PostUsersSetIsActiveJSONBody struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
}

// PostPullRequestCreateJSONRequestBody defines body for PostPullRequestCreate for application/json ContentType.
type PostPullRequestCreateJSONRequestBody PostPullRequestCreateJSONBody

// PostPullRequestMergeJSONRequestBody defines body for PostPullRequestMerge for application/json ContentType.
type PostPullRequestMergeJSONRequestBody PostPullRequestMergeJSONBody

// PostPullRequestReassignJSONRequestBody defines body for PostPullRequestReassign for application/json ContentType.
type PostPullRequestReassignJSONRequestBody PostPullRequestReassignJSONBody

// PostTeamAddJSONRequestBody defines body for PostTeamAdd for application/json ContentType.
type PostTeamAddJSONRequestBody = Team

// PostTeamDeactivateJSONRequestBody defines body for PostTeamDeactivate for application/json ContentType.
type PostTeamDeactivateJSONRequestBody PostTeamDeactivateJSONBody

// PostUsersSetIsActiveJSONRequestBody defines body for PostUsersSetIsActive for application/json ContentType.
type PostUsersSetIsActiveJSONRequestBody PostUsersSetIsActiveJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
	// (POST /pullRequest/create)
	PostPullRequestCreate(ctx echo.Context) error
	// Пометить PR как MERGED (идемпотентная операция)
	// (POST /pullRequest/merge)
	PostPullRequestMerge(ctx echo.Context) error
	// Переназначить конкретного ревьювера на другого из его команды
	// (POST /pullRequest/reassign)
	PostPullRequestReassign(ctx echo.Context) error
	// Получить статистику назначений ревьюверов по пользователям
	// (GET /stats/assignments)
	GetStatsAssignments(ctx echo.Context) error
	// Создать команду с участниками (создаёт/обновляет пользователей)
	// (POST /team/add)
	PostTeamAdd(ctx echo.Context) error
	// Деактивировать всех пользователей команды и переназначить их открытые PR
	// (POST /team/deactivate)
	PostTeamDeactivate(ctx echo.Context) error
	// Получить команду с участниками
	// (GET /team/get)
	GetTeamGet(ctx echo.Context, params GetTeamGetParams) error
	// Получить PR'ы, где пользователь назначен ревьювером
	// (GET /users/getReview)
	GetUsersGetReview(ctx echo.Context, params GetUsersGetReviewParams) error
	// Установить флаг активности пользователя
	// (POST /users/setIsActive)
	PostUsersSetIsActive(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostPullRequestCreate converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestCreate(ctx echo.Context) error {
	var err error

	ctx.Set(AdminTokenScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestCreate(ctx)
	return err
}

// PostPullRequestMerge converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestMerge(ctx echo.Context) error {
	var err error

	ctx.Set(AdminTokenScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestMerge(ctx)
	return err
}

// PostPullRequestReassign converts echo context to params.
func (w *ServerInterfaceWrapper) PostPullRequestReassign(ctx echo.Context) error {
	var err error

	ctx.Set(AdminTokenScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostPullRequestReassign(ctx)
	return err
}

// GetStatsAssignments converts echo context to params.
func (w *ServerInterfaceWrapper) GetStatsAssignments(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStatsAssignments(ctx)
	return err
}

// PostTeamAdd converts echo context to params.
func (w *ServerInterfaceWrapper) PostTeamAdd(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTeamAdd(ctx)
	return err
}

// PostTeamDeactivate converts echo context to params.
func (w *ServerInterfaceWrapper) PostTeamDeactivate(ctx echo.Context) error {
	var err error

	ctx.Set(AdminTokenScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTeamDeactivate(ctx)
	return err
}

// GetTeamGet converts echo context to params.
func (w *ServerInterfaceWrapper) GetTeamGet(ctx echo.Context) error {
	var err error

	ctx.Set(AdminTokenScopes, []string{})

	ctx.Set(UserTokenScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamGetParams
	// ------------- Required query parameter "team_name" -------------

	err = runtime.BindQueryParameter("form", true, true, "team_name", ctx.QueryParams(), &params.TeamName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter team_name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTeamGet(ctx, params)
	return err
}

// GetUsersGetReview converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsersGetReview(ctx echo.Context) error {
	var err error

	ctx.Set(AdminTokenScopes, []string{})

	ctx.Set(UserTokenScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersGetReviewParams
	// ------------- Required query parameter "user_id" -------------

	err = runtime.BindQueryParameter("form", true, true, "user_id", ctx.QueryParams(), &params.UserId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUsersGetReview(ctx, params)
	return err
}

// PostUsersSetIsActive converts echo context to params.
func (w *ServerInterfaceWrapper) PostUsersSetIsActive(ctx echo.Context) error {
	var err error

	ctx.Set(AdminTokenScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostUsersSetIsActive(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/pullRequest/create", wrapper.PostPullRequestCreate)
	router.POST(baseURL+"/pullRequest/merge", wrapper.PostPullRequestMerge)
	router.POST(baseURL+"/pullRequest/reassign", wrapper.PostPullRequestReassign)
	router.GET(baseURL+"/stats/assignments", wrapper.GetStatsAssignments)
	router.POST(baseURL+"/team/add", wrapper.PostTeamAdd)
	router.POST(baseURL+"/team/deactivate", wrapper.PostTeamDeactivate)
	router.GET(baseURL+"/team/get", wrapper.GetTeamGet)
	router.GET(baseURL+"/users/getReview", wrapper.GetUsersGetReview)
	router.POST(baseURL+"/users/setIsActive", wrapper.PostUsersSetIsActive)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xa3U4jyRV+lVIl0s5KHmzMECm+886whIthHOOVoiCECncBvWN3e/qHLEKWwGyymzAK",
	"WSkX0Uq7o9G+gMeDgweweYVTbxSdqnb/2N1tewxMtDfIdFdXnTr1ne98daqOaNWsN0yDG45NC0e0wSxW",
	"5w635H8VzurrrM7/6HLrEB9o3K5aesPRTYMWKPwCfejBFbThWryGPgygS6AHN+KcwBUM4Aba0IcLcUYz",
	"VMcvXsmOMtRgdU4L1OGsvi1/Z6jFX7m6xTVacCyXZ6hd3ed1hoM6hw1sbDuWbuzRZjNDv7K5taYlWfUf",
	"uIAu9EULeuJbZZ9owUAcE7iFgTT1EgbQkY+7cC3OE8xzbW5t69pMxjWHL6UDVyzLtMrcbpiGzfEB/4bV",
	"GzX1E9/hj6qpYRfrLyrbX774av0ZzdA6t222h08tbpuuVeXEMB2ya7qGJj3QsMwGtxyd25Guoo9Vx0eU",
	"G26dFjZpZaX4fHvlT2sblQ2aoaVy5PfzlfLqCo6NdhQ3NtZW171/t58W15+tPStWVry3ysqtzOjkQ3bH",
	"rVrgxE1lWtA+6Mvc+ZpXnbH2aobjzTK05NZqZf7K5bYz7gFm2/qewbVtix/o/C8erKN48VaZQB/acIl/",
	"xXeIH+iLM/FXIo6hCx3xWvwTOtAVx4gc8ii3sJD/HGHj8LodM13fUGZZ7BD/Z66zb0o4xbWuWpw5XCvK",
	"OeyaVp05tEA15vDHji7jw3BrNbaD0FEQjPG9tTdfDw23Vtu2lC+TDI20UXES08p2mOPaYey9KK2s0wz1",
	"UDaOnZH1HjUlbuCwT/0hM3FrPgE3G/umFQee1BX7NTgrzi/I+eO+qPP6jhc9PuR/a/FdWqC/yQYpJOtx",
	"XxZ7eS6/iYuFgPcnEkU4RQyNSDLbG3DMeN3eZlVHPwgPt2OaNc4M/HRI83Frg++mMzRIFv43mdDIcTZj",
	"GpvZ2jTf3etcwiuRNi/sTDd2TTmM7iDf0FKZlL1oJEUZn3VuOGSDWwd6lZNHFW47pMLslxnyJavVSD6X",
	"X0Z6PeCWrVh6cSG3kMNZmA1usIZOC3RpIbewhGBnzr70XLYRxHRWMap0r6lSAzqZIemvaWiSaTshDniq",
	"mis/cNv5wtQOVQ41HG7I71mjUdOrsofs1zZaFcnnIbqg7iKNYQjasB4v5nKLsQFaoEVNIzZnVnWfNsMS",
	"41Ow0pwME4+KqIqSD5QykhPL5xZnc3jDSkrxm9TNI3iX0JC7XJeArBVHN1MWSpmXRpJh6dJsxrosKlVK",
	"ZSJOYACXcIHKGhfzSe7JFF4LbEyzJ6pWY8aHf0FHSelsWN9DG8VTVymoD576PlPW/X62NR0VxWGRGoji",
	"UpnoGmE1izPtkPBvdNuxR9Zirnmin0/hv9Al4kScir9DV5yIFnTEKXRFS43Eq66lO4e0sHlEi1pdNyrm",
	"S27QwuZWcytDbbdeZ7g7ofB2uGCiJV6TUplAj0BbORI9KPcp3+EQcIWvwjK0J7+BCxiQfLwShR5cjmy2",
	"/N7FMbSRuNmejIkQ3Gy6hZOIEKbUj1Pz5XPZeg66TI7CtJiaSG8TiOvjiCn3MMQUKHiKCfDxYu5x/kll",
	"MV9YelJY/t2f74y6PF358OQFHclfMpgG4lxWD3pkaM4DkxnaM8paM4b2Gxl2XRnBw+C+gjZceXMij6An",
	"O76BWxjIakNftGRsnxMYwK0M47b4G/TE+efTh6rFFbimjtby8IM5AtasBVD2QJtPhWQKvLCvNKk6d5xn",
	"IkN8+qhHneou37scwTk0aqzKte0dRKi7TO8uyEc6T6mjDKADA3gPg/GcJRNS+lJaNDrS1hTkAm9k792x",
	"Ik4PI7wjzlTpDwMe7fskZNODa8zv8TXI13FkNKOA8nbqmESk6QFR/aTGgEvknRtJQ+dKWiAvncA1dIlf",
	"ADxgNTdJjPmNAjFWZYZhOmTIScQ0iLKBlMrKFYb5lBmarnn7sahdoiX1DeYEcQq3XtVN0ihKy55STuir",
	"NNNGqpSBdYZJ1E6VeJCSG8/q0B6iGwQ3tkNDnaIXvyOGvkldtHfiDK7HCohxgu0mfRKRymu4COztnXVb",
	"1oGHJEMckzj7uu15+u4EMPwEbXEsTsX3QRBdqGTnF0bhFsMZOohr4qWymPgT5zMn1fGePB2MMrcPV/ha",
	"ptEkjpFLQeACp4BNZDOllLvq9+jpREriRYq1s8yvWsgo2+MxSXeVOxvYuBhqO19W2cSmLjZcDtV2MG80",
	"M/6rpcirPJX+9HHgl+tGzwZcNf7Iwv8oadLbkOCeB701TqofAhrXDYfvqTpfckpPLDApO+KqY9GiYQxG",
	"34qWt3tCQ+U5T7ypEn+jsXzqw0p+HulInMZ2lLADu0UXJZwsyYAfgusPnNWcfQ9WyDpZpmnpGq7CWb2o",
	"afPoNr90uxmpLaozgAimwiVCWqzpVS5hlvZRPvrRF+aOhF+oSEkb7FCFwtT0VPEJ+Y4rRo5X2/7ULtlh",
	"1ZfcO8lLEmdDW6dw1DT66MdIuSZcRYK2Ehq5+So10cPFIHf5877Hes3o7CbVbpKKM5G0cErECZE00ZY9",
	"DI+6b6BHHgUOFD+IVhYG8M7TvRj0UtTEMgJ04UN4o4craIcZQeMSWBNL1/jhs6DtHPwwOVbHgemXjee4",
	"EDDtuc/9bd6SZhg6kBu6iZovY02eNfCksm/DlcwzHeipHHKHYRh/iwC9GdwgIKZFDJMgSdkoIUOYu7+g",
	"HNve4DNvSzQQ30MP3iFwZhSL/453p4rmjjiBrlSqSaE4VjntxStZT3/2sLOBaKEEFWeiJc6gi9o7JZ49",
	"oZikF7H9KnfkKVZw82Yz3vVBk2z0Zg46Zb7ixf9NRpxdI4yg7md4J/4BXcTEKOc8+HHJxAiYiPbMkTwl",
	"TitAhqXstAksAbGSERCy6rA2Dbholb3qt5wVv+EbXPOjN1wmU8Pfa5Vta3TDNd2BxfS3J8bupsTcofiI",
	"vVbUmKnKam/hFrdFMIArUip/5m94Ym/R3TGYS+XPxFmGwHuMltS62VRllyHgJXIjgLe5s2YX/TsXyaJL",
	"froRaj2H7AoR5i6r2Xx6TH30dZZEYEy6znHHlXLXu/cy7oK4lDAxlaS4ajhSWrDJWzjTabmfQyr/B1UI",
	"Qw2RgEyVbxYfMN/IcmpWFrkV8j0D23CBrA99dcYMH4isqF4FVeaHzIpvpi+Az6QFf1GFHG+FvNrOt3AN",
	"bXhPQiqx751A9tLuA4+xRdN/djS8H6xSJ9Ka90A1Dj2IlBNDz71KUHOr+b8AAAD//+J6bhmBLQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
